-- PostgreSQL schema for Camping Outdoors
-- Safe defaults for production backend integration.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS clients (
  id BIGSERIAL PRIMARY KEY,
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(60) NOT NULL,
  password_hash TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login_at TIMESTAMPTZ,
  UNIQUE (username)
);

-- Seed one admin account with bcrypt hash generated by pgcrypto.
INSERT INTO admin_users (username, password_hash)
VALUES ('Admin', crypt('Diablox9@', gen_salt('bf', 12)))
ON CONFLICT (username) DO NOTHING;

CREATE TABLE IF NOT EXISTS reservations (
  id BIGSERIAL PRIMARY KEY,
  reservation_code VARCHAR(40) NOT NULL,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
  lodging_type VARCHAR(30) NOT NULL,
  lodging_ref VARCHAR(50) NOT NULL,
  checkin_date DATE NOT NULL,
  checkout_date DATE NOT NULL,
  adults SMALLINT NOT NULL,
  children SMALLINT NOT NULL DEFAULT 0,
  electricity_option BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT,
  amount_tnd NUMERIC(12,2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'confirmed',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  canceled_at TIMESTAMPTZ,
  CHECK (checkout_date > checkin_date),
  CHECK (adults >= 1),
  CHECK (children >= 0),
  CHECK (status IN ('pending','confirmed','canceled')),
  UNIQUE (reservation_code)
);

CREATE INDEX IF NOT EXISTS idx_reservations_created_at
  ON reservations (created_at);

CREATE INDEX IF NOT EXISTS idx_reservations_checkin_checkout
  ON reservations (checkin_date, checkout_date);

CREATE INDEX IF NOT EXISTS idx_reservations_status
  ON reservations (status);

CREATE INDEX IF NOT EXISTS idx_reservations_client_id
  ON reservations (client_id);

-- Keep updated_at fresh.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_clients_updated_at ON clients;
CREATE TRIGGER trg_clients_updated_at
BEFORE UPDATE ON clients
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_admin_users_updated_at ON admin_users;
CREATE TRIGGER trg_admin_users_updated_at
BEFORE UPDATE ON admin_users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_reservations_updated_at ON reservations;
CREATE TRIGGER trg_reservations_updated_at
BEFORE UPDATE ON reservations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
